### ISSUE TITLE
Cannot save 

### ISSUE THREAD

**Issue by xhozt** [restorer/gloomy-dungeons-3d#8]
Shows no save slots looks squished and when I hit save it gives me (can't copy state)

**Comment by restorer** [comment]
Can it be, that your device doesn't have external storage (neither built-in, nor via an external sd-card)? To check this, you can install any commander (eg. Total Commander) and try to navigate to `/sdcard`.

_Unfortunately GD supports saving into slots only to external storage. This happened historically, and I willn't rework it by myself. However, pull requests are welcome_ 😄

**Comment by xhozt** [comment]
Like this...
